% interfata.m function file
function interfata(latitude, longitude, time_zone)



today = datetime("today","TimeZone","UTC");%gets the current date
first_midnight = dateshift(today,"start","year");%the first midnight of the year
first_midnight_next_year = dateshift(today,"start","year","next");%first midnight of the next year
middays = (first_midnight+hours(12)):caldays(1):first_midnight_next_year;%sets date to the midday of every day of the year
%Those dates and times are needed for the calculations next

y = 360*(day(middays,'dayofyear')-81)/365;%this is the formula for the solar declination
eq_of_time = minutes(9.87*sind(2*y) - 7.53*cosd(y) - 1.5*sind(y));%this is the value in minutes for the equation of time, plotted below


year_fraction = (middays - first_midnight) ./ (first_midnight_next_year - first_midnight);%year fraction at midday every day around the year
gamma = 2*3.1415*year_fraction;%transformed in radians
solar_decl = 0.006918-0.399912*cos(gamma)+0.070257*sin(gamma)-0.006758*cos(2*gamma)+0.000907*sin(2*gamma)-0.002697*cos(3*gamma)+0.00148*sin(3*gamma);
hour_angle = acosd((cosd(90.833)./(cosd(latitude).*cos(solar_decl))) - tand(latitude).*tan(solar_decl));%for the special case of sunrise or sunset, the zenith is set to 90.833 


sunrise = middays - minutes(4*(longitude + hour_angle)) - eq_of_time;
sunset  = middays - minutes(4*(longitude - hour_angle)) - eq_of_time;%all 4 of these calculations are from the PDF with solar equations provided in the documentation
%time_zone='+03:00';
sunrise.TimeZone = time_zone;
sunset.TimeZone = time_zone;%we adjust the timezone to Romania's timezone which is GMT+2, but because of daylight saving time, used ...
%between March and October, we use +3 for accurate earliest sunrise and latest sunset


% definitions as indicated in the problem3 specs
% defining the cycle of the signal
%T=1/f;
% representation range in time
%t=0:T/100:N*T;
% first function
%x1=A*sin(2*pi*f*t);
% second function
%x2=B*cos(5*2*pi*f*t);
% sum of the two functions sine and cosine
%x3=x1+x2;
% pushbuton CLOSE
uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.9 0.9 0.08 .05],...
'string','CLOSE',...
'FontName','Arial',...
'FontWeight','bold',...
'FontSize',12,...
'Callback','close');
% Text Button for variable latitude
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.9 0.65 0.08 .05],...
'Backgroundcolor',[204 153 255]./255,...
'FontSize',13,...
'FontWeight','bold',...
'String','Latitude');
% Edit Button for latitude
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.9 0.62 0.08 .05],...
'String',[latitude],...
'Callback',['latitude=','str2num(get(gco,''String''));interfata(latitude, longitude, time_zone);']);
% Text Button for variable longitude
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.9 0.55 0.08 .05],...
'backgroundcolor',[204 153 255]./255,...
'FontWeight','bold',...
'FontSize',13,...
'string','Longitude');
% Edit Button for longitude
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.9 0.52 0.08 .05],...
'String',[longitude],...
'Callback',['longitude=','str2num(get(gco,''String''));interfata(latitude, longitude, time_zone);']);
%Text Button for time_zone
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.9 0.45 0.08 .05],...
'Backgroundcolor',[204 153 255]./255,...
'FontWeight','bold',...
'FontSize',13,...
'String','Time zone');
% Edit Button for time_zone
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.9 0.42 0.08 .05],...
'String',[time_zone],...
'Callback',['time_zone=','get(gco,''String'');interfata(latitude, longitude, time_zone);']);

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.9 0.14 0.08 .05],...
'String','Reset to Initial Values',...
'FontName','Arial',...
'Callback',['latitude=','[44.42] ;interfata(46.77,23.58,"+03:00");'],...
'Callback',['time_zone=','"+03:00" ;interfata(46.77,23.58,"+03:00");'],...
'Callback',['longitude=','[26.02] ;interfata(46.77,23.58,"+03:00");']);
%setting the plot windows
%figure('Name','The value of the equation of time','NumberTitle','off');
subplot('position',[0.1 0.62 0.4 0.35]);
plot(middays,eq_of_time, "LineWidth", 2);%plot showing how the value of the equation of time changes around the year
grid on;
hold on;
xlabel('Date')
ylabel('Equation of time')
line(middays,minutes(zeros(size(middays))),'Color','r');

%figure('Name','The sunset and sunrise around the year','NumberTitle','off');
subplot('position',[0.1 0.12 0.4 0.4]);
plot(middays,timeofday(sunrise),middays,timeofday(sunset), "LineWidth", 3);%plot showing how the sunrise and sunset times vary around the year with error of about 20 minutes
grid on;
hold off;
title("Sunrise and Sunset")
xlabel("Date"); ylabel("Hours of the day")
ylim(hours([0 24]));

end