%main_interface
clear all;
close all;
% magnitude of signal 1 = sinus
A=10;
% magnitude signal 2 = cosinus
B=5;
% defining the frequency in Hz
f=50;
% number of displayed cycles
N=4;
%creating a new figure
Fig=figure('Name','Laboratory 08',...
'Units','normalized',...
'NumberTitle','off',...
'Position',[0.1 0.1 0.8 0.8],...
'Color',[0.5 0.5 0.9]);
% button indicating default values
% if the initial values are changed, the text in this button
% should be modified too!!!
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.55 0.83 0.37 .08],...
'Backgroundcolor',[0.5 0.5 0.9],...
'FontName','Arial',...
'FontWeight','bold',...
'FontSize',20,...
'String','Default values: A=10, B=5, f=50, N=4');
%call of the function file creating the graphics objects
%inside the interface
interfata(A,B,f,N);